# Flow Example

In [1]:
import os
import sys
project_root = os.path.abspath(os.path.join(os.getcwd(), '../..'))
sys.path.append(project_root)
from dotenv import load_dotenv

In [2]:
load_dotenv()

True

## Recover Files

In [3]:
from src.github_client import fetch_finance_files

In [4]:
github_repo = os.getenv('GITHUB_REPO')
github_branch = os.getenv('GITHUB_BRANCH')
github_key = os.getenv('GITHUB_TOKEN')

In [5]:
pl, bs = fetch_finance_files('SDCaFlo/finance-data', github_branch, github_key)

## Parse Files

In [16]:
import pandas as pd
from io import StringIO

### CSV

In [18]:
pl

'Account,Amount (USD)\nRevenue,100000\nCOGS,40000\nGross Profit,60000\nOperating Exp.,20000\nNet Income,40000'

In [21]:
pl_df = pd.read_csv(StringIO(pl))

In [22]:
pl_df

          Account  Amount (USD)
0         Revenue        100000
1            COGS         40000
2    Gross Profit         60000
3  Operating Exp.         20000
4      Net Income         40000

In [41]:
pl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Account       5 non-null      object
 1   Amount (USD)  5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

### MARKDOWN

In [68]:
bs

'| Account             | Amount (USD) |\n|---------------------|--------------|\n| Assets              | 200,000      |\n| Liabilities         | 100,000      |\n| Equity              | 90,000       |\n| Retained Earnings   | 35,000       |'

In [69]:
bs_data = "\n".join(
    [line for line in bs.split("\n") if not set(line.strip()) <= {"|", "-", " "} ]
)
bs_data

'| Account             | Amount (USD) |\n| Assets              | 200,000      |\n| Liabilities         | 100,000      |\n| Equity              | 90,000       |\n| Retained Earnings   | 35,000       |'

In [70]:
bs_df = pd.read_csv(StringIO(bs_data), sep='|', thousands=",").dropna(axis=1, how='all')
bs_df

    Account               Amount (USD)
0   Assets                       200000
1   Liabilities                  100000
2   Equity                        90000
3   Retained Earnings             35000

In [67]:
bs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0    Account               4 non-null      object
 1    Amount (USD)          4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

## Custom Functions

In [6]:
from src.parser import parse_csv, parse_md

In [7]:
bs_df = parse_md(bs)
pl_df = parse_csv(pl)

In [8]:
bs_df

    Account               Amount (USD)
0   Assets                       200000
1   Liabilities                  100000
2   Equity                        90000
3   Retained Earnings             35000

In [9]:
pl_df

          Account  Amount (USD)
0         Revenue        100000
1            COGS         40000
2    Gross Profit         60000
3  Operating Exp.         20000
4      Net Income         40000

## Error Raise

In [4]:
from src.github_client import update_github_issue

In [5]:
github_repo = os.getenv('GITHUB_REPO')
github_branch = os.getenv('GITHUB_BRANCH')
github_key = os.getenv('GITHUB_TOKEN')

In [6]:
example_error = 'This is an error. Test'

In [ ]:
update_github_issue(github_repo, github_key, example_error)

## LLM Contact

In [5]:
from src.clients import get_langchain_bedrock_client
from src.core.config import LLM_MODEL_ID
from langchain_core.messages import HumanMessage

In [6]:
chat = get_langchain_bedrock_client(LLM_MODEL_ID)

log: Environment: local
log: profile name : HousyProject

In [7]:
response = chat([HumanMessage('hello')])

C:\Users\Une\AppData\Local\Temp\ipykernel_24720\1487334266.py:1: LangChainDeprecationWarning: The method `BaseChatModel.__call__` was deprecated in langchain-core 0.1.7 and will be removed in 1.0. Use :meth:`~invoke` instead.
  response = chat([HumanMessage('hello')])

## EMBED TEST